language: node_js

branches:
  only:
  - master

before_install:
  - openssl aes-256-cbc -K $encrypted_key_name -iv $encrypted_iv_name -in gcp-service-key.json.enc -out gcp-service-key.json -d
  - nvm install 9

install:
  - travis_retry npm install
  - travis_retry npm install -g react-native-cli

script:
  - react-native bundle --platform ios --dev false --assets-dest ios --entry-file index.ios.js --bundle-output ios/main.jsbundle
  - zip -r react-native.zip ios/

after_success:
  - gcloud auth activate-service-account --key-file gcp-service-key.json
  - gsutil cp react-native.zip $firebase_bucket/react-native/react-native.zip
